language: php

env:
  - OPCODE_CACHE=apc

php:
  - 5.3

before_script:
  - composer self-update
  - composer update --dev

before_install:
  - curl -s http://getcomposer.org/installer | php -- --install-dir=./bin
  - php ./bin/composer.phar install --dev
